/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-fixed': '#ffdf90',
        'error': '#ba1a1a',
        'tertiary-container': '#d2a501',
        'tertiary-fixed-dim': '#f0c12c',
        'on-surface-variant': '#3f4941',
        'primary-container': '#268451',
        'tertiary': '#755b00',
        'on-tertiary': '#ffffff',
        'on-secondary-container': '#745c00',
        'on-tertiary-container': '#503d00',
        'on-error': '#ffffff',
        'secondary-fixed-dim': '#e9c349',
        'primary': '#006a3b',
        'inverse-primary': '#7ed99e',
        'inverse-surface': '#0d2c6e',
        'on-background': '#00174a',
        'outline-variant': '#becabe',
        'surface-container-low': '#f2f3ff',
        'on-secondary': '#ffffff',
        'on-surface': '#00174a',
        'background': '#faf8ff',
        'on-secondary-fixed': '#241a00',
        'surface-container-highest': '#dbe1ff',
        'on-tertiary-fixed': '#241a00',
        'secondary-container': '#fed65b',
        'primary-fixed': '#9af6b8',
        'surface-container': '#eaedff',
        'on-secondary-fixed-variant': '#574500',
        'surface-container-lowest': '#ffffff',
        'inverse-on-surface': '#eef0ff',
        'on-primary-fixed-variant': '#00522d',
        'surface-dim': '#cfd9ff',
        'surface-container-high': '#e3e7ff',
        'primary-fixed-dim': '#7ed99e',
        'surface-tint': '#006d3d',
        'surface-variant': '#dbe1ff',
        'secondary': '#735c00',
        'surface-bright': '#faf8ff',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        'on-error-container': '#93000a',
        'on-primary-fixed': '#00210f',
        'on-tertiary-fixed-variant': '#584400',
        'on-primary-container': '#f6fff4',
        'secondary-fixed': '#ffe088',
        'outline': '#6f7a70',
        'surface': '#faf8ff',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-desktop': '40px',
        xs: '4px',
        md: '16px',
        xl: '32px',
        sm: '12px',
        gutter: '24px',
        lg: '24px',
        'margin-mobile': '16px',
        base: '8px',
      },
      fontFamily: {
        montserrat: ['Montserrat', 'sans-serif'],
        'label-lg': ['Montserrat', 'sans-serif'],
        'label-sm': ['Montserrat', 'sans-serif'],
        'headline-lg': ['Montserrat', 'sans-serif'],
        'body-lg': ['Montserrat', 'sans-serif'],
        'body-md': ['Montserrat', 'sans-serif'],
        'headline-md': ['Montserrat', 'sans-serif'],
        'headline-sm': ['Montserrat', 'sans-serif'],
        'headline-lg-mobile': ['Montserrat', 'sans-serif'],
        'body-sm': ['Montserrat', 'sans-serif'],
        'display-lg': ['Montserrat', 'sans-serif'],
      },
      fontSize: {
        'label-lg': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.04em', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '700' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
};
